### ISSUE TITLE
readthedocs failing

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#108]
Recent builds are failing with:

```
% python /home/docs/checkouts/readthedocs.org/user_builds/bossdata/envs/latest/bin/pip install \
--exists-action=w -rrequirements.txt
...
Collecting fitsio==0.9.7 (from -r requirements.txt (line 6))
  Downloading fitsio-0.9.7.tar.gz (6.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kyYwC0/fitsio/setup.py", line 4, in <module>
        import numpy
    ImportError: No module named numpy
```

The solution is probably to add numpy (and scipy?) to requirements.txt, but I'm not sure what changed to make this necessary if it wasn't before.

**Comment by dkirkby** [comment]
The problem is that running `python setup.py egg_info` fails after pip-installing fitsio, because it imports numpy (see esheldon/fitsio#143).

Why is readthedocs installing all of my `requirements.txt` in the first place (e.g., [here](https://readthedocs.org/projects/bossdata/builds/6426290/))?

**Comment by dkirkby** [comment]
Remove the requirements.txt since it seems to do more harm that good:
- Rework travis config using astropy ci-helpers
- Delete `requirements.txt` in readthedocs Advanced Settings.

**Comment by dkirkby** [comment]
That still doesn't work since running `python setup.py install` still indirectly installs fitsio.

**Comment by dkirkby** [comment]
Solution is to update `setup.py` in my own fork of fitsio and then have rtd install it via:
```
git+https://github.com/dkirkby/fitsio
```
in a new `docs/rtd-pip-requirements` (which I point to in the RTD Adv Settings)
