### ISSUE TITLE
Empty spec and meta docs

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#13]
http://bossdata.readthedocs.org/en/latest/src/bossdata.meta.html

**Comment by dkirkby** [comment]
Docs for these modules are building fine locally, but the napoleon conf was missing entries to `MOCK_MODULES` for sqlite3 and numpy, which was probably the problem.

**Comment by dkirkby** [comment]
Actually, only numpy was missing since sqlite3 is part of the standard library.

**Comment by dkirkby** [comment]
The updates to `MOCK_MODULES` in 0.2.1 did not fix this.

**Comment by dkirkby** [comment]
Looking at the RTD build log files, I see:

```
/home/docs/checkouts/readthedocs.org/user_builds/bossdata/checkouts/stable/docs/src/bossdata.meta.rst:4: WARNING: autodoc: failed to import module u'bossdata.meta'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bossdata/envs/stable/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bossdata/checkouts/stable/bossdata/meta.py", line 15, in <module>
    import fitsio
ImportError: No module named fitsio
/home/docs/checkouts/readthedocs.org/user_builds/bossdata/checkouts/stable/docs/src/bossdata.spec.rst:4: WARNING: autodoc: failed to import module u'bossdata.spec'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bossdata/envs/stable/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bossdata/checkouts/stable/bossdata/spec.py", line 14, in <module>
    import fitsio
ImportError: No module named fitsio
```

Fix this by adding `fitsio` to `MOCK_MODULES`.
