### ISSUE TITLE
Protect against incomplete build of a meta db

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#45]
If `create_meta_lite` is interrupted by ^C then it leaves a files that is not usable and causes ugly errors the next time you run `bossquery`:

```
bossdata% bin/bossquery --where 'PLATE=6641' --max-rows 10 --print --verbose
Database contains 0 rows.
Traceback (most recent call last):
  File "bin/bossquery", line 71, in <module>
    main()
  File "bin/bossquery", line 48, in main
    print('Query returned {:d} rows.'.format(len(table)))
TypeError: object of type 'NoneType' has no len()
```

Presumably `create_meta_full` has the same issue but I haven't explicitly checked this.

This issue is to protect against this failure mode.  The solution is probably as simple as changing the name of the file that the `create_meta_*` methods write by appending `.building`, and then removing this suffix once the build is complete, similar to what we already do when downloading data files.  We should change permissions to be read only at the same, for good measure.

**Comment by dkirkby** [comment]
I see that sqlite3 has its own temporary file with `-journal` appended, that disappears after the final commit & close.
