### ISSUE TITLE
HTTP timeout handling

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bossdata#9]
The `bossfetch` script currently dies with:

```
Traceback (most recent call last):                                                                                                     |
  File "/usr/local/share/anaconda/bin/bossfetch", line 81, in <module>
    main()
  File "/usr/local/share/anaconda/bin/bossfetch", line 60, in main
    local_path = mirror.get(remote_path)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/bossdata/remote.py", line 181, in get
    return self.download(remote_path, local_path)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/bossdata/remote.py", line 126, in download
    for chunk in request.iter_content(chunk_size=chunk_size):
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/models.py", line 680, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='dr12.sdss3.org', port=80): Read timed out.
```

This issue is to handle this error better and investigate why it is happening and possibly add a rate-limiting option.

**Comment by dkirkby** [comment]
Another uncaught exception is "max retries exceeded":

```
Traceback (most recent call last):                                                                                                     |
  File "/usr/local/share/anaconda/bin/bossfetch", line 81, in <module>
    main()
  File "/usr/local/share/anaconda/bin/bossfetch", line 60, in main
    local_path = mirror.get(remote_path)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/bossdata/remote.py", line 181, in get
    return self.download(remote_path, local_path)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/bossdata/remote.py", line 100, in download
    request = requests.get(url, stream=True, timeout=(3.05, 27))
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/share/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='dr12.sdss3.org', port=80): Max retries exceeded with url: /sas/dr12/boss/spectro/redux/v5_7_0/spectra/lite/3940/spec-3940-55327-0332.fits (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fce8504e950>, 'Connection to dr12.sdss3.org timed out. (connect timeout=3.05)'))
```

**Comment by dkirkby** [comment]
Catch the [baseclass exception](http://docs.python-requests.org/en/latest/user/quickstart/#errors-and-exceptions) `requests.exceptions.RequestException` and convert to a `RuntimeError` in `remote.Manager.download`.

**Comment by dkirkby** [comment]
0.2.1 does not catch exceptions during the streaming phase.
